syntax = "proto3";

package user;
option csharp_namespace = "My.GRPC.Demo";

message LoginRequest{
  string username = 1;
  string password = 2;
}

message LoginResponse{
  string token = 1;
}
message RegisterRequest{
  string username = 1;
  string Email = 2;
  string Password = 3;
}
message RegisterResponse{
  string status = 1;
}
message VIPRegisterRequest{
  string name = 2;
  int32 recharge = 3;
}
message VIPRegisterResponse{
  string status =1;
}
message RegisterAdminRequest{
  string adminpassword = 1;
  string username = 2;
}
message RegisterAdminResponse{
  string status =1 ;
}
message CalculateAmountRequest{
  int32  days = 1;
}
message CalculateAmountResponse{
  repeated VIPInfo vipinfos=1;
}
message VIPInfo{
  string VIPname = 1;
  int32  recharge = 2;
}
