syntax = "proto3";
package warehouse;
option  csharp_namespace = "My.GRPC.Demo";

message WarehouseRequest{
  string address = 1;
  int32 volume = 2;
  string name = 3;
}
message WarehouseResponse{
  string status = 1;
}
message WarehouseDistanceRequest{
  string warehouseAName = 1;
  string warehouseBName = 2;
  int32  Distance = 3;
}
message WarehouseDistanceReponse{
  string status = 1;
}

message WarehousingofgoodsRequest{
  string warehouseName = 1;
  int32 volumeofgoods = 2;
  string name = 3;
}
message WarehousingofgoodsReponse{
  string remainingvolumeofthewarehouse = 1;
  string costofDay = 2;
}
message WarehouseTransportRequest{
  string warehouseAName = 1;
  string warehouseBName = 2;
  string name = 3;
}
message WarehouseTransportReponse{
  int32 Distance = 1;
  float cost = 2;
}