syntax = "proto3";
import "google/protobuf/timestamp.proto";
package user;
option csharp_namespace = "My.GRPC.Demo";

message LoginRequest{
  string username = 1;
  string password = 2;
}

message LoginResponse{
  string token = 1;
}
message RegisterRequest{
  string username = 1;
  string Email = 2;
  string Password = 3;
}
message RegisterResponse{
  string status = 1;
}
message VIPRegisterRequest{
  string name = 2;
  int32 recharge = 3;
}
message VIPRegisterResponse{
  string status =1;
}
message RegisterAdminRequest{
  string adminpassword = 1;
  string username = 2;
}
message RegisterAdminResponse{
  string status =1 ;
}
message CalculateAmountRequest{
  int32  days = 1;
}
message CalculateAmountResponse{
  repeated VIPInfo vipinfos=1;
}
message VIPInfo{
  string VIPname = 1;
  int32  recharge = 2;
}
message GetUserInfoRequest{
  int32  userID = 1;
}
message GetUserInfoResponse{
  int32  cost = 1;
  int32  costofDay = 2;
  string Userstatus = 3;
}
message GetOrdersRequest{
  int32 userId = 1;
  int32 PageIndex = 2;
  int32 PageSize = 3;
}
message GetOrdersResponse{
  repeated  OrderInfo orders = 1;
  int32 PageIndex = 2;
  int32 PageSize = 3;
  int32 Total = 4;
}
message OrderInfo{
  string WarehouseAName = 1;
  string WarehouseBName = 2;
  int32  Price = 3;
  string DriverName = 4;
  string DriverPhone = 5;
  string LicensePlateNumber = 6;
  google.protobuf.Timestamp OrderDate = 7;
}