syntax = "proto3";
package warehouse;
import  "warehouse_model.proto";
option  csharp_namespace = "My.GRPC.Demo";

service Warehouse{
  rpc WarehouseRegister(WarehouseRequest) returns (WarehouseResponse);
  rpc WarehouseDistance(WarehouseDistanceRequest) returns (WarehouseDistanceReponse);
  rpc Warehousingofgoods(WarehousingofgoodsRequest) returns (WarehousingofgoodsReponse);
  rpc WarehouseTransport(WarehouseTransportRequest) returns (WarehouseTransportReponse);
  rpc WarehouseDisplay(WarehouseDisplayRequest) returns (WarehouseDisplayReponse);
  rpc GoodsOutbound(GoodsOutboundRequest) returns (GoodsOutboundResponse);
}